version: "3.8"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: webserver
    ports:
      - "9300:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputdata:/csvserver/inputdata
    command: "/csvserver/csvserver"
