version: "3.8"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: webserver
    ports:
      - "9300:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputdata:/csvserver/inputdata
    command: "/csvserver/csvserver"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml  
